# Generated by Django 6.1 on 2026-09-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
